name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: sergeyshpadyrev/setup-idris@v1.2

      - name: Install dependencies
        run: |
          npm install-clean

      - name: Lint
        run: npm run lint

      - name: Build source
        run: |
          cd src
          idris2 --cg node Pacillus/Idris2LSP/Lex.idr -o echolex.js -p contrib
          # idris2 --cg node Pacillus/Idris2LSP/GetType.idr -o echotype.js -p contrib
          # cp build/exec/echolex.js echolex.js
          # cp build/exec/echotype.js echotype.js
          # echo -e -n "exports.Pacillus_Idris2LSP_Lex_lexAndOutput = Pacillus_Idris2LSP_Lex_lexAndOutput\n" >> echolex.js
          # echo -e -n "exports.Pacillus_Idris2LSP_GetType_process = Pacillus_Idris2LSP_GetType_process\n" >> echotype.js
          # cd ../
          # npm run compile
          # npm run esbuild
